### ISSUE TITLE
Interest in typescript typings?

### ISSUE THREAD

**Issue by retorquere** [StephenHassall/indexeddb-promise#2]
I have generated typings simply by renaming the .js files to .ts and compiling them. Is this of interest to you?

**Comment by StephenHassall** [comment]
I am not a fan of TypeScript and keep away from it. Thanks for giving it a look, but it isn't something I am interested in.

**Comment by retorquere** [comment]
In that case I'm keeping the fork I have at https://github.com/retorquere/indexeddb-promise/. I have kept the FUNDING and attribution to your name.
